#ifndef _SFCGAL_VERSION_H_
#define _SFCGAL_VERSION_H_

#cmakedefine SFCAL_VERSION_MAJOR @SFCAL_VERSION_MAJOR@
#cmakedefine SFCAL_VERSION_MINOR @SFCAL_VERSION_MINOR@
#cmakedefine SFCAL_VERSION_PATCH @SFCAL_VERSION_PATCH@

#cmakedefine SFCAL_VERSION "@SFCAL_VERSION"

#endif

