#ifndef _SFCGAL_VERSION_H_
#define _SFCGAL_VERSION_H_

#define SFCGAL_VERSION_MAJOR @SFCGAL_VERSION_MAJOR@
#define SFCGAL_VERSION_MINOR @SFCGAL_VERSION_MINOR@
#define SFCGAL_VERSION_PATCH @SFCGAL_VERSION_PATCH@

#define SFCGAL_VERSION "@SFCGAL_VERSION@"

#endif

