#ifndef _SFCGAL_VERSION_H_
#define _SFCGAL_VERSION_H_

#define SFCAL_VERSION_MAJOR @SFCGAL_VERSION_MAJOR@
#define SFCAL_VERSION_MINOR @SFCGAL_VERSION_MINOR@
#define SFCAL_VERSION_PATCH @SFCGAL_VERSION_PATCH@

#define SFCAL_VERSION "@SFCGAL_VERSION@"

#endif

